import fs from "fs";
import path from "path";

const baseUrl = "https://weblytic.cc";

const mtime = (rel: string) => {
  try {
    const stat = fs.statSync(path.join(process.cwd(), rel));
    const d = new Date(stat.mtime);
    return d.toISOString().replace(/\.\d{3}Z$/, "+00:00");
  } catch (e) {
    // Fallback if file not found in build env
    return new Date().toISOString().replace(/\.\d{3}Z$/, "+00:00");
  }
};

export async function GET() {
  const urls = [
    { loc: baseUrl, lastmod: mtime("app/page.tsx") },
    { loc: `${baseUrl}/about`, lastmod: mtime("app/about/page.tsx") },
    { loc: `${baseUrl}/careers`, lastmod: mtime("app/careers/page.tsx") },
    { loc: `${baseUrl}/faq`, lastmod: mtime("app/faq/page.tsx") },
    { loc: `${baseUrl}/terms`, lastmod: mtime("app/terms/page.tsx") },
    { loc: `${baseUrl}/privacy`, lastmod: mtime("app/privacy/page.tsx") },
    { loc: `${baseUrl}/refund-policy`, lastmod: mtime("app/refund-policy/page.tsx") },
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `\t<url>
\t\t<loc>${u.loc}</loc>
\t\t<lastmod>${u.lastmod}</lastmod>
\t</url>`).join("\n")}
</urlset>
<!-- XML Sitemap generated by Weblytic -->`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=0, must-revalidate",
    },
  });
}
